### ISSUE TITLE
custom vars

### ISSUE THREAD

**Issue by vivrt** [aliyun/fun#102]
Is there way to use custom vars like
```
custom:
  dataSetBucket: 'images-roaddamage' 
  listBucket: 'dataset-list'
  listKey: 'hk.json'
  resultBucket: 'hk-result'
  frontendBucket: 'hk-frontend'

```
?
