### ISSUE TITLE
支持定义多个table store的表格

### ISSUE THREAD

**Issue by zxkane** [aliyun/fun#122]
如果像下面这样同时声明多个table，fun的语法检查会报错。

```yaml
  my-table-store:
    Type: 'Aliyun::Serverless::TableStore'
    Properties:
      ClusterType: HYBRID
      Description: dingtalk events
    bpm_raw:
      Type: 'Aliyun::Serverless::TableStore::Table'
      Properties:
        PrimaryKeyList:
          - Name: processInstanceId
            Type: STRING
    approvals:
      Type: 'Aliyun::Serverless::TableStore::Table'
      Properties:
      PrimaryKeyList:
        - Name: createdTime
          Type: LONG
        - Name: userId
          Type: STRING
        - Name: processInstanceId
          Type: STRING
```
