### ISSUE TITLE
fun配置EnvironmentVariables时 value为整数会部署失败

### ISSUE THREAD

**Issue by Arlenmbx** [aliyun/fun#161]
函数计算的环境变量传入的参数需要全部为string类型，而模版中如果value为int部署会失败，如下：

```
        EnvironmentVariables:
          StringTypeValue1: 123
          StringTypeValue2: test
          PathValue: /tmp/test
```

需要强制为123加上单引号/双引号才成功，如 StringTypeValue1: ‘123’。理想情况下，EnvironmentVariables的value不应该受单/双引号的限制，默认全部为string。
