### ISSUE TITLE
"fun local start" does not act like api gateway

### ISSUE THREAD

**Issue by sm-github** [aliyun/fun#173]
Right now testing [Using Function Compute as API Gateway's backend service](https://www.alibabacloud.com/help/doc-detail/54788.htm#Create%20and%20define%20a%20Function%20Compute%20backend%20service%20API) **locally** is very difficult.

Could it please be made similar to testing [http triggers locally](https://github.com/aliyun/fun/blob/master/lib/commands/local/http-support.js#L40).

For example:

If I have a resource like this
```yaml
apiGroup:
  Type: "Aliyun::Serverless::Api"
  Properties:
    StageName: RELEASE
    DefinitionBody:
      "/gateway-example":
        get:
          x-aliyun-apigateway-api-name: example
          x-aliyun-apigateway-fc:
            arn: acs:fc:::services/${gatewayExample.Arn}/functions/${functionExample.Arn}/
            timeout: 10000
```

I would like to be able to run `fun local start`
and then curl this

```shell
curl -i --get --include 'http://localhost:8000/gateway-example'  -H 'Authorization:APPCODE 你自己的AppCode'
```
