### ISSUE TITLE
'fun init' with custom template throws error

### ISSUE THREAD

**Issue by Joldnine** [aliyun/fun#256]
my custom template:
```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  {{ service }}:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: 'function'
    {{ projectName }}:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: python3
        CodeUri: 'index.py'

  {{ service }}_api_group:
    Type: 'Aliyun::Serverless::Api'
    Properties:
      StageName: RELEASE
      DefinitionBody:
        '/predict':
          get:
            x-aliyun-apigateway-api-name: {{ service }}_predict
            x-aliyun-apigateway-fc:
              arn: acs:fc:::services/${{{ service }}.Arn}/functions/${{{ projectName }}.Arn}/
```

Run
```
$ fun init [my template folder]
```

Got log:
```
Start rendering template...
+ /Users/myname/develop/github.com/test
+ /Users/myname/develop/github.com/test/index.py
+ /Users/myname/develop/github.com/test/template.yml
Unexpected token )
```

Please help!
