### ISSUE TITLE
template.yml如何定义api开启https或WEBSOCKET？

### ISSUE THREAD

**Issue by senseluo** [aliyun/fun#52]
类似  
```yaml
   DefinitionBody:
        '/': # request path
          get: # http method
            x-aliyun-apigateway-api-name: hello_get # api name
            x-aliyun-apigateway-fc:
              arn: acs:fc:::services/${capi.Arn}/functions/${helloworld.Arn}/
            x-aliyun-apigateway-visibility: PUBLIC
```

能给一个更多参数的示例吗？
谢谢~
