### ISSUE TITLE
FUN创建OTS表失败

### ISSUE THREAD

**Issue by 2903710916** [aliyun/fun#74]
![image](https://user-images.githubusercontent.com/33981218/44007997-a817ef74-9ed0-11e8-91bb-efa24dc6b46c.png)

```
对应的YAML文件示例为：
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:  
  xxxxxxx:
    Type: 'Aliyun::Serverless::TableStore'
    Properties:
      ClusterType: SSD
      Description: 'xxxxxx'
    __session__:
      Type: 'Aliyun::Serverless::TableStore::Table'
      Properties:
          PrimaryKeyList:
            - Name: id
              Type: STRING
    __user__:
      Type: 'Aliyun::Serverless::TableStore::Table'
      Properties:
          PrimaryKeyList:
            - Name: id
              Type: STRING
    __cache__:
      Type: 'Aliyun::Serverless::TableStore::Table'
      Properties:
          PrimaryKeyList:
            - Name: id
              Type: STRING
```
